### ISSUE TITLE
Support for Missing Official Format: Base Game + Rebel vs Imperium Only

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#24]
This is a little known, fully playtested and officially supported format, that is not available in the AI for no good reason. It would gives us a whole new format to play and learn that i'd like to explore and popularize a bit. Requires:

1) Train the AI for this new format.

2) Slightly adjust the **New...** dialog. The cleanest solution might be to just add a 4th **Game Option** "Disable The Gathering Storm", default off, and greyed out unless Rebel vs Imperium is selected in Expansion Level. Maybe better and more intuitive would be to have it in the Expansion Level, as "Rebel vs Imperium only".

3) Possible side-effects i don't know about: especially cards.txt. Possibly save game file, exporting games, campaign file. Might be easier or harder depending on whether it's made as an Expansion Level or a Game Option flag.

**Comment by bnordli** [comment]
Interesting.. There shouldn't be a problem with cards.txt, it will be a problem giving this format an id, though. I think it would be best represented internally by a flag, as you describe. How it will be represented in the UI can be debated, I think it is time for a revamp of the expansion selection, since the arcs are not represented in any way.

**Comment by Marsux** [comment]
internally, it seems at first sight easy to do after the refactoring of the cards.txt format:
- increase the number of expansion
- in the succ_in_arc table, add 6 to the list of expansions affected by 0 and 2, and a 6th list limited to -1
- check that all tests on expansion number are compatible with this, adapt if necessary.

So I don't think a flag is necessary, just a new (pseudo-)expansion.

**Comment by Marsux** [comment]
I have been working on the subject. I think I have a first implementation, I have been able to play some games with it, but still have a weird segfault just at the beginning of the game that seems to happen due to the absence of trained networks.

I have started training the networks, should be good to go tomorrow evening.

I'll let bnordli decided whether this can still be incorporated to the forthcoming release.

**Comment by Marsux** [comment]
See Pull request #26

**Comment by Marsux** [comment]
I just pushed the trained nets on the same branch. Do I have to do an additional pull request?

**Comment by bnordli** [comment]
Great, thanks! I'll take a look. 

No, the new commit is automatically added to the existing PR.

**Comment by bnordli** [comment]
Merged as 11e5c95cb
