### ISSUE TITLE
rftg.plingri.net Not The Default And Requires Typing It Out

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#30]
If rftg.plingri.net will be the only way to play XI atm, the XI client should default to this network the first time you launch the connect to network dialog after installation.

In the longrun, the Server name text box should be a combo box that remembers servers, so that less savvy users aren't wholly in the dark about how to connect to keldon.net and such.

**Comment by bnordli** [comment]
This is not really easy to solve, but this is the current status:
1) If rftg has previously been installed on the computer, the previous settings file is used. This does not mention rftg.plingri.net, and there are no simple ways to merge the new server name into an existing settings file. (The other alternative would be to delete all previous settings and start with the default again.)
2) If rftg has not been previously installed on the computer (or the settings file is deleted before installation), rftg.plingri.net is listed as the default server, with keldon.net as an alternative.

In any scenario, the connect dialog actually does remember all previously entered server names, and autocompletes after pressing the first letter. We have discussed using a combo box, but decided not to (because we do not really want to have multiple servers running).

Also, I don't plan for rftg.plingri.net to permanently become the new rftg server, so I don't want to introduce all kinds of special handling in the code.

**Comment by dsnvwlmnt** [comment]
OK. Just to be clear then, when i uninstalled rc1 and then installed rc2, rftg.plingri.net was no longer remembered, i had to spell it out by hand. I'm unclear if that's the correct behavior but i suspect not. All my other settings were properly remembered.

**Comment by bnordli** [comment]
That was because rc1 was using 'rftg9' as a settings file. rc2 is using 'rftg', so it didn't remember anything from rc1 (my mistake for not telling) and reverted back to scenario 1 above. Installers cannot have characters in versions, so all have been using 0.9.5, causing all sorts of problems, like forcing uninstalls. The installation and upgrade paths will be much smoother for non-beta players.

Thanks for being a beta tester, enduring these sorts of stuff ;)

**Comment by Marsux** [comment]
I find that the issue is valid, and should be managed better. It is confusing that when upgrading rftg, the new default server is not available by default. I assume a lot of players will be upgrading and confronted with the problem. Most of them never bothered with the server selection.

A quick fix would consist in:
- add a new "custom_server" preference, initialized to False
- in the Connect dialog, add a check_box linked to this preference value
- when the custom_server variable is false, the server hostname and port entries are not sensitive, and the default server is used, for the time being plingri
- when the custom_server is true, the entries are sensitive, and their content is used

Does this look good?

**Comment by bnordli** [comment]
Ok, I'll make sure the rftg.plingri.net server is set as the new server after upgrade. The logic is this: If rftg.plingri.net is not seen in the preferences file, it is added to the list of servers, and also set as the default value in the dialog box. (So later, if the user connects to keldon.net, rftg.plingri.net is still in the servers list, but keldon.net will be the default value, until the user connects to another server again.)

Wrapping everything up for release now!
