### ISSUE TITLE
Clean up code.

### ISSUE THREAD

**Issue by o01eg** [bnordli/rftg#47]
Should source tree contains `configure`, `Makefile.in` and other autogenerated files with created by `autoreconf`?

**Comment by bnordli** [comment]
Not really. I build mainly on Windows, so haven't done much to the Unix build setup.

Feel free to remove the generated files in your PR!

There is one Makefile.in in the network folder as well!

**Comment by Marsux** [comment]
I think yes.
On linux, usually you are able to build with only configure and make.

**Comment by bnordli** [comment]
Oh, I see, there are two pre-build steps, autoreconf and configure. In this case, perhaps it is best to keep the output of the first step, as Marsux said. (I am not very familiar with this process.)

**Comment by gchambers419** [comment]
Speaking as someone who is familiar with Linux build processes, the configure.in file is in the repository so that people doing development can update it as needed.  The generated configure file is committed so that a non-developer can do a checkout and build without the full autotools suite being installed.  

In the days before publicly visible repositories, the generated files might not have been checked in, but would still be part of the source code tarball.

**Comment by bnordli** [comment]
Thanks for the input! Let's keep them, then! 

I'll take a look at your PR when I have time.
