### ISSUE TITLE
Uplift code and Abandoned Alien Uplift camp does not draw cards on production

### ISSUE THREAD

**Issue by karl616** [bnordli/rftg#49]
I am quite new to RftG, but I think I found a small bug. The combination 

Uplift code
Abandoned alien uplift camp
and the production phase

did not draw me any cards, which I would have expected. 

This was found in version 0.9.4, but I couldn't find anything in the change log fixing this. Attaching a save file.

[upliftCode.txt](https://github.com/bnordli/rftg/files/1151108/upliftCode.txt)

**Comment by dsnvwlmnt** [comment]
Not a bug, you draw for Chromosome worlds not Uplift worlds. Game mechanic bugs are exceedingly rare on the Keldon AI. You can safely assume that if you think you find a rules bug, it's working correctly.

**Comment by ayao44** [comment]
@dsnvwlmnt, while I agree that many "bugs" end up not being so (I can speak to that personally), I would still find it better to report it rather than let it slip.

That said, there was a FAQ on the program, or a link to it online somewhere that mentioned a list a commonly missed things (e.g. how Rebel Cantina is NOT supposed to count towards the Propaganda Edge most goal since that looks at REBEL military worlds, but Rebel Cantina is a Rebel NON-military world)

**Comment by karl616** [comment]
@ayao44 

http://keldon.net/rftg/faq.html
was this what you had in mind?

@dsnvwlmnt 
I see, I thought the chromosome was the uplift-symbol. Thank you for clarifying.
