### ISSUE TITLE
Hide Password with ***** in Connect to Server Dialog

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#6]
Any chance you can hide the password with ***** in the Connect to Server dialog? I'm going to be streaming Race a lot and i'd rather not display my password.

**Comment by bnordli** [comment]
Added a manual preference to hide password. In `%AppData%\rftg`, add the following line under `[multiplayer]`
```
hide_password=true
```

**Comment by dsnvwlmnt** [comment]
Thanks!

**Comment by dsnvwlmnt** [comment]
Oh, i'd suggest making 'true' the default if it isn't. No accidental password displays. Not a problem for me because of my setup, but...

**Comment by bnordli** [comment]
Since the password is sent in plain text to the server (and previously it
was stored in plain text on the server), it is displayed in clear text to
the users as well, in order to encourage them not to reuse a personal or
sensitive password.

I won't be fixing this.

18. nov. 2016 21:52 skrev "Serge Levert" <notifications@github.com>:
